version: '3'

services:
    app:
        container_name: simple-flask-api
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - $HOST_PORT:$DOCKER_PORT  #host_port:docker_port