version: '3'

services:
    app:
        image: simple-flask-app-k8s
        container_name: simple-flask-api
        build:
            dockerfile: ./Dockerfile
            context: .
        env_file: .env
        ports:
            - $PORT:$PORT  #host_port:docker_port